/**
 * Le catalogue RBAC du back, recopié. La source de vérité reste
 * `BAE-Back/database/rbac_catalog.ts` — ici c'est un miroir, dont le seul rôle
 * est de faire échouer à la compilation un `permissionGuard('cliet:read')`
 * qu'aucun test ne rattraperait : une permission mal orthographiée n'est jamais
 * détenue, donc l'entrée disparaît de la barre et la page devient injoignable,
 * en silence.
 *
 * Quand le back ajoute une permission, l'ajouter ici aussi. Un miroir en retard
 * ne casse rien de ce qui existe : il empêche seulement d'utiliser la nouvelle.
 */
export type Permission =
  | 'presence:write'
  | 'presence:read'
  | 'stock:read'
  | 'stock:write'
  | 'stock:delete'
  | 'product:read'
  | 'product:write'
  | 'product:delete'
  | 'supplier:read'
  | 'supplier:write'
  | 'supplier:delete'
  | 'restock:read'
  | 'restock:write'
  | 'restock:delete'
  | 'log:read'
  | 'event:matching'
  | 'event:settle'
  | 'assignment:write'
  | 'assignment:delete'
  | 'member:read'
  | 'member:write'
  | 'member:delete'
  | 'role:read'
  | 'role:write'
  | 'role:delete'
  | 'voucher:read'
  | 'voucher:write'
  | 'voucher:delete'
  | 'menu:read'
  | 'menu:write'
  | 'menu:delete'
  | 'category:read'
  | 'category:write'
  | 'category:delete'
  | 'good:read'
  | 'good:write'
  | 'good:delete'
  | 'furniture:read'
  | 'furniture:write'
  | 'furniture:delete'
  | 'event:read'
  | 'event:write'
  | 'event:delete'
  | 'job:read'
  | 'job:write'
  | 'job:delete'
  | 'fast-pass:read'
  | 'fast-pass:write'
  | 'fast-pass:delete'
  | 'transaction:read'
  | 'order:read'
  | 'order:serve'
  | 'order:write'
  | 'order:delete'
  | 'order:discount'
  | 'client:read'
  | 'client:write'
  | 'client:delete'
  | 'subscription:read'
  | 'subscription:write'
  | 'subscription:delete'
  | 'ticket:read'
  | 'ticket:write';
