services:
  dashboard:
    image: registry.eirb.fr/bae/erp-dashboard:latest
    container_name: bae-erp-dashboard
    ports:
      - '8080:80'
    restart: unless-stopped

  public:
    image: registry.eirb.fr/bae/erp-public:latest
    container_name: bae-erp-public
    ports:
      - '8081:80'
    restart: unless-stopped
