export const AppRoutes = {
  home: '',
  presences: 'presences',
  myPresences: 'presences/my',
  adherents: 'adherents',
  stocks: 'stocks',
  stocksScanner: 'stocks/scanner',
  recettes: 'recettes',
  coordination: 'coordination',
  logistique: 'logistique',
  caisse: 'caisse',
  precommandesAdmin: 'precommandes',
  soiree: 'soiree',
  soireeLive: 'soiree/live',
  soireeBilan: 'soiree/bilan',
  paiements: 'paiements',
  analyse: 'analyse',
  tickets: 'tickets',
  notifications: 'notifications',
  parametres: 'parametres',
  parametresSecurite: 'parametres/securite',
  parametresPreferences: 'parametres/preferences',
  equipe: 'equipe',
  etats: 'etats',
  login: 'login',
} as const;
