name: Build and deploy
on:
  push:
    tags:
      - 'v*'

jobs:
  create-env:
    name: Create environment file
    permissions:
      contents: read
    runs-on: ubuntu-latest
    concurrency: production
    steps:
      - name: Generate environment.ts
        run: |
          cat <<EOF > src/environments/environment.ts
          export const environment = {
          production: true,
          apiUrl: "${{ vars['BAE_API_URL'] }}",
          EOF

  build-and-push:
    name: Build and push Docker image
    permissions:
      id-token: write
    uses: Eirbware/.github/.github/workflows/build-and-publish.yml@master
    with:
      file: './Dockerfile'
      image_name: ${{ github.repository }}
    secrets:
      registry_username: ${{ secrets.registry_username }}
      registry_api_key: ${{ secrets.registry_api_key }}

  deploy:
    name: Deploy on Portainer
    needs: [build-and-push]
    uses: Eirbware/.github/.github/workflows/deploy-stack.yml@master
    secrets:
      portainer_stack_webhook: ${{ secrets.portainer_stack_webhook }}
      wireguard_conf: ${{ secrets.wireguard_conf }}
